### ISSUE TITLE
Syntax error at 'Optional' at init.pp:53

### ISSUE THREAD

**Issue by sinall** [voxpupuli/puppet-letsencrypt#101]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.7
- Ruby: 1.8.7.374-5
- Distribution: centos-release-6-3.el6.centos.9.x86_64
- Module version: v2.0.1

## How to reproduce (e.g Puppet code you use)
```
class certbot {

class { ::letsencrypt:
  email => 'xxx@xxx.com',
}

letsencrypt::certonly { 'install certbot':
  domains => ['www.xxx.com'],
  plugin => 'apache',
  manage_cron => true,
  cron_success_command => 'service httpd restart',
}

}

```

## What are you seeing
puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class ::letsencrypt at /etc/puppet/modules/certbot/manifests/init.pp:5 on node ay131218175445754fb6z
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

## What behaviour did you expect instead
Success without error

## Any additional information you'd like to impart
Same code works with v1.1.0.

**Comment by ekohl** [comment]
Our modules only work with Puppet 4 and higher. That's the reason we bumped the version to 2.0.0. With 3.8.7 you might be able to use the future parser but that's not really something we test. There is also no intent to continue supporting the Puppet 3 compatible branches because it's EOL and we've upgraded. We recommend you to do the same.
